
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipsmart_api
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on: []
